### ISSUE TITLE
User Media doesn't go away

### ISSUE THREAD

**Issue by syeshchenko** [syeshchenko/InstaFriends#24]
1) Keep pressing No until you see all of the candidates

Expected:
Once you reach end of the candidates, you should see "No more candidates" 

Actual: 
You see "No more candidates" but the user media of the last candidates still below.  

Issue is not reproducible 100% of the time, please try multiple times. 

<img width="1920" alt="untitled" src="https://cloud.githubusercontent.com/assets/2295144/16901387/3ac6e0d4-4c10-11e6-9c14-a00a33c62723.png">

**Comment by Hamabama** [comment]
is it specific to Chrome only or persistent across all the browsers?

**Comment by syeshchenko** [comment]
Tried only in chrome so far

**Comment by Hamabama** [comment]
Ну ты даёшь

**Comment by Hamabama** [comment]
Couldn't reproduce. It was probably due to #25 issue and it was fixed. Please try again with the latest update.
